### ISSUE TITLE
Latest updates for the HP EliteDesk 800 G4/G5 Mini

### ISSUE THREAD

**Issue by TonyC5** [Shadowghost/elitedesk-800-g4-mini-macos-efi#2]
Deeveedee is no longer maintaining the Tonymacx86 threads.  The latest updates can be found [here](https://www.insanelymac.com/forum/topic/343937-guide-catalina-big-sur-monterey-ventura-on-hp-elitedesk-800-g4g5-mini-the-perfect-macmini81-hackintosh/).

**Comment by Shadowghost** [comment]
Thanks, I have it bookmarked. I need to find some time to update the repo.
